---
- name: Install System Packages
  apt: pkg={{ item }}
       update_cache=yes
       state=latest
  with_items: "{{ system_packages }}"

- name: Set timezone to '{{timezone}}'
  template: src=timezone.tpl dest=/etc/timezone

- name: Set timezone to '{{timezone}}' (cont.)
  file: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack to '{{locale}}'
  shell: locale-gen {{locale}}
