---
- name: Install MySQL Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Update root password for all root accounts
  mysql_user: >
    name=root 
    host={{ item }} 
    check_implicit_admin=yes 
    password={{ mysql_root_password }} 
    login_user=root 
    login_password={{ mysql_root_password }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Destroy database '{{ mysql_database }}'
  mysql_db: >
    name={{ mysql_database }} 
    state=absent 
    login_user=root 
    login_password={{ mysql_root_password }}

- name: Create database '{{ mysql_database }}'
  mysql_db: > 
    name={{ mysql_database }} 
    state=present 
    login_user=root 
    login_password={{ mysql_root_password }}

- name: Create MySQL user '{{ mysql_user }} '
  mysql_user: > 
    name={{ mysql_user }} 
    password={{ mysql_password }} 
    priv={{ mysql_database }}.*:ALL 
    state=present 
    login_user=root 
    login_password={{ mysql_root_password }}

- name: Import '{{ mysql_backup_filename }}'
  mysql_db: >
    name={{ mysql_database }}
    state=import
    login_user=root
    login_password={{ mysql_root_password }}
    target=/vagrant/src/sql/{{ mysql_backup_filename }}
